- name: loops
  hosts: local
  connection: local 
  tasks:
  - name: print names 
    ansible.builtin.debug:
      msg: "Hello, {{ item }}"
    loop: # Else we can use with_items 
    - Suresh 
    - Ramesh 
    - Joseph 
    - Raheem