- name: install packages
  hosts: frontend
  become: yes 
  tasks:
  - name: install packages 
    package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx 
    - zip 
