- name: install packages
  hosts: frontend
  become: yes 
  tasks:
  - name: install packages 
    package:
      name: "{{ item.a }}"
      state: "{{ item.b }}"
    loop:
    - {a: mysql ,b: present}
    - {a: nginx ,b: present}
    - {a: zip ,b: present}
