- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Rahim,Joseph"
  tasks:
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "Hello, {{ person | default('Ramesh') }}"
    
  - name: Print names
    debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list 
    vars:
      course:
        name: ansible
        duration: 10 HR 
        trainer: Siva Kumar 
    debug:
      msg: "Course Information: {{ course | dict2items }}"
  
