- name: install nginx 
  hosts: dynamic_frontend 
  serial: 3
  become: yes 
  tasks:
  - name: install nginx 
    dnf:
      name: nginx 
      state: installed

  - name: run nginx 
    service: 
      name: nginx
      state: restarted
      enabled: yes
 